// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmtzwecmjzqiwyzyldjz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdHp3ZWNtanpxaXd5enlsZGp6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNDYzMzUsImV4cCI6MjA3MzYyMjMzNX0.nR5_1hQCxMFltnaa_3DexWVdykcdP4no-4h0rTZ00rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});